################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
################################################################################

property:
  gpu-id: 0
  net-scale-factor: 0.00392156862745098
  # tlt-model-key: tlt_encode
  # tlt-encoded-model: ../../../../samples/models/Primary_Detector/resnet18_trafficcamnet.etlt
  model-engine-file: /workspace/sources/apps/sample_apps/deepstream-test1/yolo_nas_m_coco_fp16.engine
  labelfile-path: /workspace/DeepStream-Yolo/labels.txt
  # int8-calib-file: ../../../../samples/models/Primary_Detector/cal_trt.bin
  force-implicit-batch-dim: 1
  batch-size: 1
  network-mode: 1
  num-detected-classes: 80
  interval: 0
  gie-unique-id: 1
  uff-input-order: 0
  uff-input-blob-name: input_1
  output-blob-names: boxes;scores;classes
  #scaling-filter=0
  #scaling-compute-hw=0
  cluster-mode: 2
  infer-dims: 3;640;640

class-attrs-all:
  pre-cluster-threshold: 0.2
  topk: 20
  nms-iou-threshold: 0.5