version: "3"

services:
  deepstream70:
    image: nvcr.io/nvidia/deepstream:7.0-gc-triton-devel
    container_name: deepstream70
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    restart: always
    network_mode: host
    shm_size: "4gb"
    env_file: .env
    volumes:
      - ${DS_HOME_DIR}:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME_DIR}/.Xauthority:/root/.Xauthority
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /dev/snd:/dev/snd
    devices:
      - /dev/snd:/dev/snd
    environment:
      - USER=${USER}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - DISPLAY=${DISPLAY}
      - "QT_X11_NO_MITSHM=1"
      
    stdin_open: true
    tty: true
    
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
                                                                                                                                                     
    command: sleep infinity