################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2022-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
################################################################################

rest-server:
  within_multiurisrcbin: 0

server-app-ctx:
  #Use single uri in uri_list for server-app-ctx to start the sample application.
  #i.e. no comma separted uri's to be used)
  # uri_list: file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_720p.mp4
  # uri_list: rtsp://210.99.70.120:1935/live/cctv007.stream,rtsp://210.99.70.120:1935/live/cctv008.stream,rtsp://210.99.70.120:1935/live/cctv009.stream,rtsp://210.99.70.120:1935/live/cctv010.stream,rtsp://210.99.70.120:1935/live/cctv011.stream,rtsp://210.99.70.120:1935/live/cctv012.stream,rtsp://210.99.70.120:1935/live/cctv013.stream,rtsp://210.99.70.120:1935/live/cctv014.stream,rtsp://210.99.70.120:1935/live/cctv015.stream,rtsp://210.99.70.120:1935/live/cctv016.stream,rtsp://210.99.70.120:1935/live/cctv017.stream,rtsp://210.99.70.120:1935/live/cctv018.stream,rtsp://210.99.70.120:1935/live/cctv019.stream,rtsp://210.99.70.120:1935/live/cctv020.stream,rtsp://210.99.70.120:1935/live/cctv021.stream,rtsp://210.99.70.120:1935/live/cctv022.stream,rtsp://210.99.70.120:1935/live/cctv023.stream,rtsp://210.99.70.120:1935/live/cctv024.stream,rtsp://210.99.70.120:1935/live/cctv025.stream,rtsp://210.99.70.120:1935/live/cctv026.stream,rtsp://210.99.70.120:1935/live/cctv027.stream,rtsp://210.99.70.120:1935/live/cctv028.stream,rtsp://210.99.70.120:1935/live/cctv029.stream,rtsp://210.99.70.120:1935/live/cctv030.stream,rtsp://210.99.70.120:1935/live/cctv031.stream
  # uri_list: rtsp://210.99.70.120:1935/live/cctv001.stream,rtsp://210.99.70.120:1935/live/cctv002.stream,rtsp://210.99.70.120:1935/live/cctv003.stream,rtsp://210.99.70.120:1935/live/cctv004.stream
  # uri_list: rtsp://210.99.70.120:1935/live/cctv007.stream
  httpIp: "localhost"
  httpPort: "9001"
  pipeline_width: 640
  pipeline_height: 360
  maxBatchSize: 9
  # batched_push_timeout: 500000
  batched_push_timeout: 33333
  live_source: 1
  drop_pipeline_eos: 1

multiurisrcbin:
  #comma separated uri (no semicolon at the end). For ex- uri1,uri2,uriN
  #parsed inside nvmultiurisrcbin
  # uri-list: file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_720p.mp4
  # uri-list: rtsp://210.99.70.120:1935/live/cctv007.stream,rtsp://210.99.70.120:1935/live/cctv008.stream,rtsp://210.99.70.120:1935/live/cctv009.stream,rtsp://210.99.70.120:1935/live/cctv010.stream
  uri-list: rtsp://210.99.70.120:1935/live/cctv007.stream,rtsp://210.99.70.120:1935/live/cctv008.stream,rtsp://210.99.70.120:1935/live/cctv009.stream,rtsp://210.99.70.120:1935/live/cctv010.stream,rtsp://210.99.70.120:1935/live/cctv011.stream,rtsp://210.99.70.120:1935/live/cctv012.stream,rtsp://210.99.70.120:1935/live/cctv013.stream,rtsp://210.99.70.120:1935/live/cctv014.stream,rtsp://210.99.70.120:1935/live/cctv015.stream,rtsp://210.99.70.120:1935/live/cctv016.stream,rtsp://210.99.70.120:1935/live/cctv017.stream,rtsp://210.99.70.120:1935/live/cctv018.stream,rtsp://210.99.70.120:1935/live/cctv019.stream,rtsp://210.99.70.120:1935/live/cctv020.stream,rtsp://210.99.70.120:1935/live/cctv021.stream,rtsp://210.99.70.120:1935/live/cctv022.stream
  # uri-list: rtsp://210.99.70.120:1935/live/cctv007.stream,rtsp://210.99.70.120:1935/live/cctv008.stream,rtsp://210.99.70.120:1935/live/cctv009.stream,rtsp://210.99.70.120:1935/live/cctv010.stream,rtsp://210.99.70.120:1935/live/cctv011.stream,rtsp://210.99.70.120:1935/live/cctv012.stream,rtsp://210.99.70.120:1935/live/cctv013.stream,rtsp://210.99.70.120:1935/live/cctv014.stream,rtsp://210.99.70.120:1935/live/cctv015.stream
  # uri-list: rtsp://210.99.70.120:1935/live/cctv007.stream
  port: 9001
  live-source: 1
  width: 640
  height: 360
  # batched-push-timeout: 500000
  batched-push-timeout: 33333
  max-batch-size: 16
  #To simulate nvvideoconvert specific REST APIs change disable-passthrough: 1
  disable-passthrough: 0
  drop-pipeline-eos: 1
  #Enable rtsp reconnections properties for rtsp source(s).
  # rtsp-reconnect-interval: 1
  # rtsp-reconnect-attempts: 1000
  #To demonstrate the new nvstreammux config-file usage
  config-file-path: config_new_nvstreammux.txt

osd:
  process-mode: 0
  display-text: 1

tiler:
  width: 1280
  height: 720

sink:
  sync: 0
  qos: 0

encoder:
  codec: 1 # codec=1 h264, codec=2 h265
  enable: 0 #Disabled, Set to 1 to enable encoder pipeline in the sample application.

# Inference using nvinfer:
primary-gie:
  plugin-type: 0
  config-file-path: dsserver_pgie_config.yml

## Inference using nvinferserver:
#primary-gie:
#  plugin-type: 1
#  config-file-path: dsserver_pgie_nvinferserver_config.txt
